### ISSUE TITLE
eslint(import/no-extraneous-dependencies) for @expo/vector-icons imports

### ISSUE THREAD

**Issue by parthv21** [benmosher/eslint-plugin-import#1289]
I am importing **FontAwesome** from **@expo/vector-icon.**

I get this linter error: 

>'@expo/vector-icons' should be listed in the project's dependencies. Run 'npm i -S @expo/vector-icons' to add iteslint(import/no-extraneous-dependencies)

How do I prevent this error?

**Comment by ljharb** [comment]
`npm install --save @expo/vector-icons`?

**Comment by ahmedelgabri** [comment]
I have the exact same problem & I do have all the dependencies in `package.json` in proper sections. I have `react` for example is in `dependencies` & still complaining.

These are all the eslint related packages I'm using in that project

```
    "babel-eslint": "10.0.1",
    "eslint": "5.15.1",
    "eslint-config-airbnb": "17.1.0",
    "eslint-config-prettier": "4.1.0",
    "eslint-import-resolver-webpack": "0.11.0",
    "eslint-plugin-flowtype": "3.4.2",
    "eslint-plugin-import": "2.16.0",
    "eslint-plugin-jsx-a11y": "6.2.1",
    "eslint-plugin-prettier": "3.0.1",
    "eslint-plugin-react": "7.12.4",
    "eslint-plugin-react-hooks": "1.5.0",
```

**Comment by ahmedelgabri** [comment]
This is not happening in `2.14.0` started to happen from `2.15.0`

**Comment by benmosher** [comment]
fixed in 2.16? see solution in #1301?

**Comment by ahmedelgabri** [comment]
For me, it's still not working. Not in `2.16` or even `2.18`

Vim:
<img width="838" alt="Screen Shot 2019-06-29 at 09 26 16" src="https://user-images.githubusercontent.com/63876/60381186-034e4380-9a51-11e9-82e5-33fc6f464f6a.png">

VSCode
<img width="848" alt="Screen Shot 2019-06-29 at 09 28 50" src="https://user-images.githubusercontent.com/63876/60381188-034e4380-9a51-11e9-8215-b9414aaa13fe.png">

Node console

`2.18`
<img width="462" alt="Screen Shot 2019-06-29 at 09 28 08" src="https://user-images.githubusercontent.com/63876/60381187-034e4380-9a51-11e9-95a1-6e4c4d64678e.png">

`2.16`
<img width="478" alt="Screen Shot 2019-06-29 at 09 33 15" src="https://user-images.githubusercontent.com/63876/60381189-03e6da00-9a51-11e9-9a1d-26b1957d09ff.png">

**Comment by ahmedelgabri** [comment]
Ignore that, sorry. I added the rule inside `settings` instead of `rules`.

**Comment by tianfeng65** [comment]
The 2.22.1 version still has this problem, when I use **@ant-design/icons**

**Comment by KyleAsaff** [comment]
in `.eslintrc.json`
```
    "settings": {
      "import/core-modules": [
        "@expo/vector-icons"
      ]
    }
```
should solve the error message

**Comment by tickietackie** [comment]
> in `.eslintrc.json`
> 
> ```
>     "settings": {
>       "import/core-modules": [
>         "@expo/vector-icons"
>       ]
>     }
> ```
> 
> should solve the error message

Could you explain, what this is doing?

Does this solve the issue EsLint is claiming here? 
"If an import declaration's source is extraneous (it's not written in package.json), the program works in local, but will not work after dependencies are re-installed. It will cause troubles to your team/contributors. This rule disallows import declarations of extraneous modules. (https://github.com/mysticatea/eslint-plugin-node/blob/v11.1.0/docs/rules/no-extraneous-import.md)"

**Comment by ljharb** [comment]
The solution remains https://github.com/benmosher/eslint-plugin-import/issues/1289#issuecomment-464302909 as far as I’m aware.

**Comment by RomanDavlyatshin** [comment]
> in `.eslintrc.json`
> 
> ```
>     "settings": {
>       "import/core-modules": [
>         "@expo/vector-icons"
>       ]
>     }
> ```
> 
> should solve the error message

@KyleAsaff  It does not really "solve" the issue, more like masking it.  [import/core-modules](https://github.com/benmosher/eslint-plugin-import#importcore-modules) option "tricks" ESlint into considering module being resolved. When in reality, it could be not installed at all. 😿 

@tickietackie it's just basically disabling the rule for the selected list of packages.

**Comment by ljharb** [comment]
I'm pretty sure that the solution to this is https://github.com/benmosher/eslint-plugin-import/issues/1289#issuecomment-757569586.

If, with v2.23.4, you're still seeing issues around this, please comment and it can be reopened.

**Comment by Egge7** [comment]
> I'm pretty sure that the solution to this is [#1289 (comment)](https://github.com/import-js/eslint-plugin-import/issues/1289#issuecomment-757569586).
> 
> If, with v2.23.4, you're still seeing issues around this, please comment and it can be reopened.

Yes and no. While this will fix it, there is really no reason for @expo/vector-icons/Ionicons to be in package.json as its part of the expo core package...
