### ISSUE TITLE
v2.20.2 break  ` no-extraneous-dependencies` with webpack alias

### ISSUE THREAD

**Issue by githoniel** [benmosher/eslint-plugin-import#1712]
```
OS: Microsoft Windows [Version 10.0.18362.720]
Node: v10.14.2
ESLINT: v5.16.0
```

In my webpack config, I set a alias name for one of our scoped package for short

```
alias: {
  'fish': '@sdp.nd/fish'
}
```

In eslint-plugin-import@2.20.1, it works well while I got `no-extraneous-dependencies` in eslint-plugin-import@2.20.2.

```
import { Button } from 'fish'
```

After debug, I found these code make things different

```js
// src/core/importType.js
// Line 31
// v2.20.2
// subPath = 'node_modules'
// path = 'C:\Users\yj\Desktop\test-collection\demo-base\node_modules\@sdp.nd\fish\es\index.js'
function isSubpath(subpath, path) {
  const normPath = path.replace(/\\/g, '/')
  const normSubpath = subpath.replace(/\\/g, '/').replace(/\/$/, '')
  if (normSubpath.length === 0) {
    return false
  }
  const left = normPath.indexOf(normSubpath)
  const right = left + normSubpath.length
  return left !== -1 &&
        (left === 0 || normSubpath[0] !== '/' && normPath[left - 1] === '/') &&
        (right >= normPath.length || normPath[right] === '/')
}
```

`isSubpath` return `true ` in v2.20.2 while return `false` in v2.20.1.

I found both v2.20.1 and v2.20.2 will report `no-extraneous-dependencies` on ubuntu and I think v2.20.2 is right, it just fix path error in Window.

I found that 

```js
// lib\rules\no-extraneous-dependencies.js
// line 124
const resolved = resolve(name, context) // name == 'fish'
if (!resolved) { return } // resolve = 'C:\Users\yj\Desktop\base-demo-0317\node_modules\@sdp.nd\fish\es\index.js'

const splitName = name.split('/')
const packageName = splitName[0][0] === '@'
    ? splitName.slice(0, 2).join('/')
    : splitName[0]
```

packageName should be `@sdp.nd\fish` not `fish` in this case.

**Comment by ljharb** [comment]
Thanks; a PR with a failing test case would be helpful.

**Comment by githoniel** [comment]
@ljharb I found tests of this project can only run in Linux and it is OK with test case I add, while I do not know how to debug code only in terminal in Linux...

But I can provide a reproduce repo here

https://github.com/githoniel/eslint-import-webpack-alias-bug

It both fail in Windows/Linux

**Comment by madisabel** [comment]
Confirming - starting from v2.20.1 path aliases are not working. I've been actually defining path aliases in tsconfig.json file which have been resolved perfectly until v2.20.1

**Comment by br0p0p** [comment]
I'm experiencing this issue as well. Reverting to v2.20.0 fixed it for me.

**Comment by IShotTheSheriff** [comment]
Still experiencing this issue with 2.22.1, thanks @br0p0p for advice to downgrading to 2.20.0.

Hope it will be addressed at some point.

**Comment by githoniel** [comment]
@IShotTheSheriff  2.20.0 will always skip `alias` detect in window and will report error on other platform.
hope this will be fix soon~~~

**Comment by vvanpo** [comment]
I've had this plugin pinned at v2.20.0 for a long time due to this bug, but tried upgrading to v2.23.2 and that appears to fix it. @githoniel could you confirm whether this bug is still reproducible with the latest version? Otherwise I think we can close this.

**Comment by ljharb** [comment]
I'll close it for now, but will be happy to reopen if anyone's still experiencing problems.
