### ISSUE TITLE
v2.23 causes `no-extraneous-dependencies` errors for related `@types/` packages that aren't imported

### ISSUE THREAD

**Issue by neefrehman** [benmosher/eslint-plugin-import#2078]
Since upgrading to v2.23 I'm seeing lot's of errors in my TypeScript codebase related to `@types` dependencies, even though they are not directly being imported. for example:

```ts
import React from "react";
import * as THREE from "three";
import { OrbitControls } from "three/examples/jsm/controls/OrbitControls";
```

Is throwing:

```shell
  3:1  error  '@types/react' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  4:1  error  '@types/three' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
  5:1  error  '@types/three' should be listed in the project's dependencies, not devDependencies  import/no-extraneous-dependencies
```

**Comment by marjorg** [comment]
Can confirm this. Reverting to 2.22.1 for now

**Comment by buu700** [comment]
Possibly related issue: I'm now getting `error  'rxjs/operators' should be listed in the project's dependencies. Run 'npm i -S rxjs/operators' to add it  import/no-extraneous-dependencies`, with `rxjs/operators` being a path within the `rxjs` package.

**Comment by ljharb** [comment]
I believe this may be a duplicate of #2065, and possibly related to #2058.

**Comment by JuanpaG94** [comment]
Can confirm this. Not only for `@types/` dependencies but everything that has other packages inside the dependency.
For example `styled-components/native` or similar.

**Comment by cloudagon** [comment]
Thanks for reporting this. I thought I was going crazy.

**Comment by henryjin3** [comment]
Is this addressed by #2097?

**Comment by VirajKanse** [comment]
is this fixed yet or not?
Am still facing same issue for @chakra-ui/layout & other components

**Comment by ljharb** [comment]
Yes, it’s fixed in v2.23.4. If you’re still seeing it, please file a new issue.
