### ISSUE TITLE
Why isn't "eslint-import-resolver-node" listed in `eslint-module-utils`'s peerDependencies?

### ISSUE THREAD

**Issue by onlywei** [benmosher/eslint-plugin-import#828]
This plugin does not work with `pnpm` because it relies on NPM3's flat `node_modules` structure. Please see: https://github.com/pnpm/pnpm/issues/739, where there is a reproducible repo.

**Comment by ljharb** [comment]
First off, if something works with npm but not an npm clone, then the npm clone is broken.

It's listed as a dependency (https://github.com/benmosher/eslint-plugin-import/blob/master/package.json#L83), and this project works in npm 2 (which doesn't flatten like npm 3+ does), so I'm not sure why that would be an issue.

**Comment by ljharb** [comment]
After rereading the linked issue, https://github.com/pnpm/pnpm/issues/739#issuecomment-300612332 is about `eslint-module-utils`, not `eslint-plugin-import` - so you're asking about https://github.com/benmosher/eslint-plugin-import/blob/master/utils/package.json - which yes, should probably specify everything it requires as a dep or a peer+dev dep.

**Comment by benmosher** [comment]
see: https://github.com/pnpm/pnpm/issues/739#issuecomment-301077475

@ljharb: after reading the linked comment, I'm curious what ideas you have to resolve this. I wouldn't be against just spec'ing `npm install eslint-plugin-import eslint-import-resolver-node` in the README if you think that wouldn't be too much drag on the user install experience.

I like that it works out of the box for most people, thus the current setup.

**Comment by ljharb** [comment]
https://github.com/pnpm/pnpm/issues/739#issuecomment-301084388 Seems reasonable.

**Comment by stereokai** [comment]
So what's the verdict on this? :)

**Comment by ljharb** [comment]
From https://github.com/pnpm/pnpm/issues/739#issuecomment-301084388 via https://github.com/benmosher/eslint-plugin-import/issues/828#issuecomment-301099241:
> eslint-plugin-import should pass its __dirname to eslint-module-utils, and it should resolve from that dir. The resolve-from package might help.

PRs are welcome.

**Comment by zkochan** [comment]
An update on this problem. I did a pull request to [resolve](https://github.com/substack/node-resolve/pull/131) to add a `preserveSymlinks` option to it. Could this package use `resolve` with `preserveSymlinks: false` instead of the custom [utils/resolve](https://github.com/benmosher/eslint-plugin-import/blob/master/utils/resolve.js) module?

**Comment by ljharb** [comment]
Since I maintain both `resolve` and collaborate on `eslint-plugin-import`, I'm naturally in favor of that.

**Comment by stereokai** [comment]
@ljharb Sounds great!

**Comment by dandv** [comment]
Any progress on this?

**Comment by ljharb** [comment]
This seems to have been fixed by #1591.

**Comment by dsnoeck** [comment]
This issue is not resolved. Using pnpm: 7.27.1 & eslint-plugin-import: 2.26.0
